data:extend({
    {
        type = "bool-setting",
        name = "pypp-dev-mode",
        setting_type = "startup",
        default_value = false,
        hidden = true,
        order = "e",
    },
    {
        type = "bool-setting",
        name = "pypp-create-cache",
        setting_type = "startup",
        default_value = false,
        hidden = true,
        order = "e",
    },
    {
        type = "bool-setting",
        name = "pypp-verbose-logging",
        setting_type = "startup",
        default_value = false,
        hidden = true,
        order = "e",
    },
    {
        type = "bool-setting",
        name = "pypp-big-inventory-gui",
        setting_type = "startup",
        default_value = false,
        order = "e",
    },
    {
        type = "bool-setting",
        name = "pypp-compactified-recipe-tooltips",
        setting_type = "startup",
        default_value = true,
        order = "e",
    },
    {
        type = "bool-setting",
        name = "pypp-extended-recipe-signals",
        setting_type = "startup",
        default_value = false,
        order = "e",
    },
    {
        type = "bool-setting",
        name = "pypp-tests",
        setting_type = "startup",
        default_value = false,
        order = "e",
    },
    {
        type = "bool-setting",
        name = "pypp-no-globals",
        setting_type = "startup",
        default_value = false,
        order = "e",
    },
    {
        type = "double-setting",
        name = "pypp-click-lock-duration",
        setting_type = "runtime-per-user",
        default_value = 0.5,
        minimum_value = 0,
        maximum_value = 10,
        order = "a"
    }
})
