return {
    ammo_category_node = 1,
    electricity_node = 2,
    entity_node = 3,
    equipment_grid_node = 4,
    fluid_fuel_node = 5,
    fluid_node = 6,
    fuel_category_node = 7,
    item_node = 8,
    recipe_category_node = 9,
    recipe_node = 10,
    resource_category_node = 11,
    start_node = 12,
    technology_node = 13,
}
