name: Test

on:
  push:
    branches:
    - main
    - Frozen
    paths-ignore:
      - 'cached-configs/**'

permissions:
  contents: read

jobs:
  test-push:
    name: Push
    uses: pyanodon/pyanodontests/.github/workflows/pytest.yml@v1.5.0
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      test_branch: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
